version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/postgis
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  postgis-data:
